name: Python CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Test or compile fallback
        run: |
          if ls tests/test_*.py >/dev/null 2>&1; then
            pytest -q
          else
            python -m py_compile \$(git ls-files '*.py')
